export const CHATBOT_SERVICES = {
  income_certificate: {
    id: 'income_certificate',
    label: 'Income Certificate',
    category: 'certificates',
    aliases: ['income certificate', 'income proof certificate', 'salary certificate'],
    keywords: ['income', 'salary', 'certificate', 'tehsildar', 'affidavit'],
    documents: ['Aadhaar card', 'Address proof', 'Income affidavit or salary slip', 'Passport-size photograph'],
    steps: [
      'Visit your state e-district portal or nearest Tehsildar office',
      'Fill the income certificate application form',
      'Upload or attach required documents',
      'Submit application and keep acknowledgement number',
      'Track status online or via local office',
    ],
    office: 'Tehsildar office / e-District portal',
    time: '7-21 working days (varies by state)',
  },
  caste_certificate: {
    id: 'caste_certificate',
    label: 'Caste Certificate',
    category: 'certificates',
    aliases: ['caste certificate', 'sc certificate', 'st certificate', 'obc certificate', 'category certificate'],
    keywords: ['caste', 'sc', 'st', 'obc', 'reservation', 'certificate'],
    documents: ['Aadhaar card', 'Address proof', 'Caste proof of self/family', 'School record (if available)', 'Passport-size photograph'],
    steps: [
      'Apply via e-District portal or SDM/Tehsildar office',
      'Fill caste certificate form with family details',
      'Attach identity, address, and caste proof documents',
      'Submit and complete local verification if requested',
      'Download certificate after approval',
    ],
    office: 'SDM / Tehsildar / Revenue Department',
    time: '10-30 working days',
  },
  domicile_certificate: {
    id: 'domicile_certificate',
    label: 'Domicile Certificate',
    category: 'certificates',
    aliases: ['domicile certificate', 'residence certificate', 'nativity certificate'],
    keywords: ['domicile', 'residence', 'nativity', 'local resident', 'proof of residence'],
    documents: ['Aadhaar card', 'Address proof', 'Residence proof (rent agreement/utility bill)', 'Affidavit (state dependent)', 'Photograph'],
    steps: [
      'Open your state citizen service portal or visit Tehsildar office',
      'Fill the domicile/residence certificate form',
      'Upload required residence and ID proofs',
      'Submit application and note reference number',
      'Collect or download certificate after verification',
    ],
    office: 'Tehsildar / SDM office / State service portal',
    time: '7-20 working days',
  },
  passport: {
    id: 'passport',
    label: 'Passport',
    category: 'ids',
    aliases: ['passport', 'new passport', 'passport renewal', 'india passport'],
    keywords: ['passport', 'psk', 'police verification', 'travel document'],
    documents: ['Aadhaar card', 'Address proof', 'Date of birth proof', 'PAN (optional but useful)', 'Previous passport (for renewal)'],
    steps: [
      'Create account on Passport Seva portal',
      'Fill online application and pay fees',
      'Book appointment at Passport Seva Kendra (PSK)',
      'Visit PSK with originals and biometrics',
      'Complete police verification and track dispatch',
    ],
    office: 'Passport Seva Kendra (PSK) / Passport Seva Portal',
    time: '2-6 weeks (depends on police verification)',
  },
  ration_card: {
    id: 'ration_card',
    label: 'Ration Card',
    category: 'documents',
    aliases: ['ration card', 'food security card', 'nfsa ration card'],
    keywords: ['ration', 'food card', 'nfsa', 'pds', 'subsidy'],
    documents: ['Identity proof of head of family', 'Address proof', 'Family member details', 'Passport-size photos', 'Income details (if required)'],
    steps: [
      'Apply on state food and civil supplies portal or local office',
      'Select new ration card application',
      'Add household details and upload documents',
      'Submit application and keep acknowledgement',
      'Collect card or check digital status after approval',
    ],
    office: 'Food and Civil Supplies Department',
    time: '15-30 working days',
  },
  driving_license: {
    id: 'driving_license',
    label: 'Driving License',
    category: 'ids',
    aliases: ['driving license', 'driving licence', 'dl', 'learner license', 'llr'],
    keywords: ['license', 'licence', 'dl', 'learner', 'rto'],
    documents: ['Aadhaar card', 'Address proof', 'Age proof', 'Passport-size photograph', 'Medical certificate (if applicable)'],
    steps: [
      'Apply on Parivahan portal for learner license',
      'Appear for learner test and receive learner license',
      'After required period, apply for driving test',
      'Visit RTO for biometric and driving skill test',
      'Download or receive driving license after approval',
    ],
    office: 'RTO / Parivahan Sewa portal',
    time: '2-6 weeks',
  },
  complaint_filing: {
    id: 'complaint_filing',
    label: 'Civic Complaint Filing',
    category: 'complaints',
    aliases: ['file complaint', 'civic complaint', 'municipal complaint', 'public grievance', 'register complaint'],
    keywords: ['complaint', 'grievance', 'issue', 'municipal', 'public'],
    documents: ['Issue description', 'Location details', 'Photo/video evidence (if any)', 'Contact details'],
    steps: [
      'Open complaint section in JAN-VAANI',
      'Describe issue with location and date',
      'Attach available evidence',
      'Submit complaint and save reference number',
      'Track status through department portal/app',
    ],
    office: 'Municipal body / District grievance cell / JAN-VAANI complaint desk',
    time: '3-30 days depending on issue category',
  },
};

export const FALLBACK_CATEGORIES = ['Certificates', 'Complaints', 'Documents'];

export const FALLBACK_SUGGESTIONS = [
  'Income Certificate',
  'Caste Certificate',
  'Domicile Certificate',
  'Passport',
  'Driving License',
];
